---
title: "Biochar and Soil Microbial Inocula Effects on Plant Growth and C mineralization - with graphs"
author: "Ariane L. Peralta, 2017 Microbial Ecology Class"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
  - \usepackage{graphics}
output: 
  pdf_document:
  fig_caption: true
---

Project Description: 

# Initial Setup
```{r}
rm(list=ls())
setwd("~/GitHub/BGE_ME_EXPT")
se <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
ci <- function(x, ...){1.96 * sd(x,na.rm = TRUE)}

# Code Dependencies
require("reshape")
require("ggplot2")
```

# Input Data
```{r}
data1 <- read.csv("../data/2017_BGE_ME_expt_DATA.csv", header=TRUE)
str(data1)
#NOTE: all parametric tests were run without testing for assumptions to simplify
#code for the class - so the 'proper' way to run these stats is to test for
#normality and homogeneity of variances or modeling fitting approaches
```

# Data Analysis - Carbon Mineralization
```{r}
# hyp testing and plot - 3-way ANOVA - all interactions
data.lm <- lm(Cmin~Biochar*Microbe*Plant, data=data1)
anova(data.lm)
summary(data.lm)

#only Biochar and Microbe main effects significant
data.lm2 <- lm(Cmin~Biochar+Microbe, data=data1)
anova(data.lm2)
summary(data.lm2)

#graphing C mineralization by microbes only
p <- ggplot(data1, aes(x=Biochar, y=Cmin, color=Microbe))+geom_point()
p1=p+geom_smooth(method="lm",aes(fill=Microbe))
p1 + theme_bw() 
p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1.25)) + theme(axis.ticks.length=unit(0.3,"cm")) + xlab("Percent Biochar") + ylab("C mineralization \n(micro-g CO2-C/g soil/day)") 
ggsave("../figures/Cmin.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```
# Data Analysis - Shoot Biomass
```{r}
data.lm <- lm(ShootMass_g~Biochar*Microbe, data=data1)
anova(data.lm)
summary(data.lm)

#graphing shoot biomass microbes x biochar
p <- ggplot(data1, aes(x=Biochar, y=ShootMass_g, color=Microbe))+geom_point()
p1=p+geom_smooth(method="lm",aes(fill=Microbe))
p1 + theme_bw() 
p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1.25)) + theme(axis.ticks.length=unit(0.3,"cm")) + xlab("Percent Biochar") + ylab("Shoot biomass (g)") 
ggsave("../figures/Shoot.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```
# Data Analysis - Root Biomass
```{r}
data.lm <- lm(RootMass_g~Biochar*Microbe, data=data1)
anova(data.lm)
summary(data.lm)

#graphing root biomass microbes x biochar
p <- ggplot(data1, aes(x=Biochar, y=RootMass_g, color=Microbe))+geom_point()
p1=p+geom_smooth(method="lm",aes(fill=Microbe))
p1 + theme_bw() 
p1 + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1.25)) + theme(axis.ticks.length=unit(0.3,"cm")) + xlab("Percent Biochar") + ylab("Root biomass (g)") 
ggsave("../figures/Root.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

# Data Analysis - testing moisture impact on shoot biomass
```{r}
#testing moisture impact on shoot biomass - MICROBES addition only
attach(data1)
newdata <- data1[ which(Microbe=='Microbes'),]
detach(data1)
data.lm <- lm(ShootMass_g~PercentMoisture, data=newdata)
summary(data.lm)

#testing moisture impact on shoot biomass - NO microbe addition only
attach(data1)
newdata2 <- data1[ which(Microbe=='NoMicrobes'),]
detach(data1)
data.lm2 <- lm(ShootMass_g~PercentMoisture, data=newdata2)
summary(data.lm2)

#need to graph root biomass on y-axis and moisture on x-axis by microbe treatment
p <- ggplot(data1, aes(x=PercentMoisture, y=RootMass_g, color=Microbe))+geom_point()
p1=p+geom_smooth(method="lm",aes(fill=Microbe))
p1 + theme_bw() + xlim(0,200)
p1 + theme_bw() + xlim(0,200) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +theme(axis.title=element_text(vjust=1,size=16,face="bold"), axis.text=element_text(size=14), axis.text.x = element_text(vjust=0.65, hjust=0.5, size=14), panel.border = element_rect(colour = "black",size=1.25)) + theme(axis.ticks.length=unit(0.3,"cm")) + xlab("Percent Moisture") + ylab("Root biomass (g)") 
ggsave("../figures/Moisture-Root.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```