---
title: "Biochar and Soil Microbial Inocula Effects on Plant Growth and C mineralization"
author: "Ariane L. Peralta, 2017 Microbial Ecology Class"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
  - \usepackage{graphics}
output: 
  pdf_document:
  fig_caption: true
---

Project Description: 

# Initial Setup
```{r}
rm(list=ls())
setwd("~/GitHub/BGE_ME_EXPT")
se <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
ci <- function(x, ...){1.96 * sd(x,na.rm = TRUE)}
```

# Input Data
```{r}
data1 <- read.csv("../data/2017_BGE_ME_expt_DATA.csv", header=TRUE)

#NOTE: all parametric tests were run without testing for assumptions to simplify
#code for the class - so the 'proper' way to run these stats is to test for
#normality and homogeneity of variances or modeling fitting approaches
```

# Data Analysis - Carbon Mineralization
```{r}
#testing 3-factor ANOVA and interactions
data.lm <- lm(Cmin~Biochar*Microbe*Plant, data=data1)
anova(data.lm)
summary(data.lm)

#only Biochar and Microbe main effects significant
data.lm2 <- lm(Cmin~Biochar+Microbe, data=data1)
anova(data.lm2)
summary(data.lm2)
```
# Data Analysis - Shoot Biomass
```{r}
data.lm <- lm(ShootMass_g~Biochar*Microbe, data=data1)
anova(data.lm)
summary(data.lm)
```
# Data Analysis - Root Biomass
```{r}
data.lm <- lm(RootMass_g~Biochar*Microbe, data=data1)
anova(data.lm)
summary(data.lm)
```
# Data Analysis - testing moisture impact on shoot biomass
```{r}
#testing moisture impact on shoot biomass - MICROBES addition only
attach(data1)
newdata <- data1[ which(Microbe=='Microbes'),]
detach(data1)
data.lm <- lm(ShootMass_g~PercentMoisture, data=newdata)
summary(data.lm)

#testing moisture impact on shoot biomass - NO microbe addition only
attach(data1)
newdata2 <- data1[ which(Microbe=='NoMicrobes'),]
detach(data1)
data.lm2 <- lm(ShootMass_g~PercentMoisture, data=newdata2)
summary(data.lm2)
```
